### ISSUE TITLE
[TESTING] Create a mocked profile input script

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/cis#16]
We'll need a way to simulate change events to the CIS library.  This task captures the following:

- [x] Generates a mocked user profile
- [x] Inputs to CIS first lambda function
- [x] Validates success / failure ( should have both know fail and known success test cases )

^^ Arguably the last task in this card is an end to end test with a greater set of faked profiles.  @tyearns suggest marking this one done and creating a new task for "end to end test with a number of user profiles"

**Comment by andrewkrug** [comment]
@johngian this seems like as good a place to start as any... mocking event.json stuff to the input validator.  Should we add a fake_profile function to the CIS core library.

**Comment by andrewkrug** [comment]
nemo is working on this story right now so I'm assigning and linking the method that he will attempt in an effort to keep the card up to date. https://github.com/json-schema-faker/json-schema-faker

**Comment by johngian** [comment]
PR opened here:
#37
