### ISSUE TITLE
Cannot run the tests

### ISSUE THREAD

**Issue by armenzg** [mozilla-iam/cis#396]
Running the tests fails with `flake8` missing [1]

You can use `pipenv` to help manage virtual environments and packages rather than requiring installing `flake8` globally or needing to use a Docker image. `pipenv` does not pollute your global installation.

Steps taken:
```
pipenv install
pipenv install flake8 tox
pipenv run make test-tox
```

After I manage to get the tests running it fails with:
```
E               FileNotFoundError: [Errno 2] No such file or directory: 'dynalite': 'dynalite'
```

[1]
```
Armens-MacBook-Pro:cis armenzg$ cd python-modules/
Armens-MacBook-Pro:python-modules armenzg$ make test-tox
/Applications/Xcode.app/Contents/Developer/usr/bin/make test-tox -C cis_aws
flake8 setup.py
/bin/bash: flake8: command not found
make[1]: *** [.flake] Error 127
make: *** [cis_aws] Error 2
```

**Comment by andrewkrug** [comment]
Hi @armenzg you need to have dynalite and kinesalite on your machine to run the test suite.

**Comment by andrewkrug** [comment]
FYI we've not really leaned into pipenv on the project as a _strong_ choice with the assumption that users know how to manage their base python dependencies.  Foundational things like tox, flake8, etc are fair to assume exist for most python devs.

**Comment by gdestuynder** [comment]
note, while we may use Pipenv at some point for now a simple thing to help self-management would be to add flake8 and pytest-cov (and maybe some other things) to `tox.ini`'s dependencies. then the only dep becomes tox itself

**Comment by gdestuynder** [comment]
tests are now running in docker so these should work in any env :)
