### ISSUE TITLE
Document starting point for developers

### ISSUE THREAD

**Issue by johngian** [mozilla-iam/cis#4]

**Comment by andrewkrug** [comment]
Blocked by #1

**Comment by andrewkrug** [comment]
I started also on a sample of using apex with functions calling other lambdas.  Documenting my progress here: https://github.com/andrewkrug/apex-prototype

**Comment by andrewkrug** [comment]
Blocked by #5 waiting decision on IAM delegations.

**Comment by andrewkrug** [comment]
Starting point documented in http://github.com/mozilla-iam/cis_functions
