### ISSUE TITLE
`aud` property looks strange

### ISSUE THREAD

**Issue by helfi92** [mozilla-iam/cis#423]
Not sure if this is the right repo for this issue...

When I decode the jwt that I get after logging in with SSO, I get:

```js
{
  // ...
  'https://sso.mozilla.com/claim/AAI': [ '2FA' ],
  'https://sso.mozilla.com/claim/AAL': 'MEDIUM',
  'https://sso.mozilla.com/claim/README_FIRST':
   'Please refer to https://github.com/mozilla-iam/person-api in order to query Mozilla IAM CIS user profile data',
  given_name: 'Hassan',
  family_name: 'Ali',
  nickname: 'Hassan Ali',
  name: 'Hassan Ali',
  picture:
   'https://s.gravatar.com/avatar/09d98c475aaac392a3457c1a156ae45f?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fha.png',
  updated_at: '2019-04-24T19:01:59.490Z',
  iss: 'https://auth.mozilla.auth0.com/',
  sub: 'ad|Mozilla-LDAP|haali',
  aud: 't2bF4DuTfGLfdtaC4omAgTG9pU6ZlpGY',
  iat: 1556132520,
  exp: 1556737320
}
```

The `aud` property looks strange. Is this expected? I was under the assumption `aud` should be `api.sso.mozilla.com`. Thanks.

**Comment by gdestuynder** [comment]
`t2bF4DuTfGLfdtaC4omAgTG9pU6ZlpGY`  is the audience for a token issued to, well, `t2bF4DuTfGLfdtaC4omAgTG9pU6ZlpGY` (which is taskcluster netlify's client id)
this means only this task cluster property will validate it - its probably an SPA :)

**Comment by helfi92** [comment]
Ah, makes sense! Thanks for the explanation.
