### ISSUE TITLE
person_api_v1 returns null

### ISSUE THREAD

**Issue by helfi92** [mozilla-iam/cis#482]
[Some users](https://bugzilla.mozilla.org/show_bug.cgi?id=1595749#c4) are having trouble logging in to Taskcluster. From [comment 7](https://bugzilla.mozilla.org/show_bug.cgi?id=1595749#c7), I am suspecting the PersonAPI is not always finding the relevant profile for the user since https://sso.mozilla.com/info shows `person_api_v1` as null. See [comment 8](https://bugzilla.mozilla.org/show_bug.cgi?id=1595749#c8) for the screenshot. Any idea what's happening? Apologies if the issue was filed in the wrong place.

**Comment by helfi92** [comment]
@gdestuynder @andrewkrug,  any idea if this is a bug?

**Comment by gdestuynder** [comment]
the value on `person_api_v1` can/should be ignored :)

**Comment by gdestuynder** [comment]
following up on https://bugzilla.mozilla.org/show_bug.cgi?id=1595749#
