### ISSUE TITLE
Tests failing because botocore can't connect to endpoint

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/cis#492]
`E           botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://localhost:32078/"`

Tests began failing around the time #489 was merged.

I'm not sure what the cause is but tests now fail.

**Comment by floatingatoll** [comment]
Tests no longer fail in this manner. I de-paralleled them and found a missing dependency in one of the modules that, when added, repaired the "start a network listener" function in the tests. Fixed by #529.
