### ISSUE TITLE
Enhance logging

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/cis#51]
See https://github.com/mozilla-iam/cis_functions/pull/5#pullrequestreview-41339272

**Comment by andrewkrug** [comment]
@gdestuynder this is actually maybe needed to generate better metrics.  Can we define the requirements around logging a little more one on one.  I think that this should be in scope for the OKR release.

**Comment by gdestuynder** [comment]
Defining logging is definitely part of the task I think (I don't have a plan without looking at the code)

**Comment by johngian** [comment]
I suggest we keep using python infrastructure for logging but also use different log levels. Then for ``DEBUG`` level we can sent json formatted messages of the full event. From what i see cloudwatch can parse/filter json logs.

**Comment by johngian** [comment]
That said maybe we can send ``DEBUG`` level to mozdef. Thoughts?

**Comment by gdestuynder** [comment]
@pwnbus (probably have input for mozdef/preference/references)
