### ISSUE TITLE
Deserialization Issues from CIS_HRIS connector

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/cis#81]
The new CIS HRIS connector is failing at decrypting / de-serializing the profile and I can't figure out why.

**Comment by andrewkrug** [comment]
https://github.com/andrewkrug/cis_hris_publisher/blob/master/hris_publisher/publish.py follows the same logic as in Mozillians.org and I get the following traceback when trying to push profiles:

@johngian I may need your help debugging.... 


```
Incorrect padding: Error
Traceback (most recent call last):
File "/var/task/main.py", line 33, in handle
encrypted_profile_data = json.loads(base64.b64decode(event.get('profile')))
File "/var/lang/lib/python3.6/base64.py", line 87, in b64decode
return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

**Comment by andrewkrug** [comment]
@gdestuynder as per your suggestion on this one I matched the python versions exactly and I still have serialization issues.

**Comment by gdestuynder** [comment]
would recommend checking the output of event.get('profile') is truly base64 in various places where it's called.
i may be wrong but i would assume in some cases it is and in others its not

**Comment by andrewkrug** [comment]
This was actually the unicode issue.  Closing this out.
